{{- if and (not .Values.githubToken.existingSecret) .Values.githubToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.githubToken.secretName }}
type: Opaque
stringData:
  {{ .Values.githubToken.secretKey }}: {{ .Values.githubToken.value | quote }}
{{- end }}
